language: java

services:
  - docker

jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

after_success:
  - docker build -t bgpark82/game-multiplication ./multiplication
  - docker build -t bgpark82/game-eureka-server ./eureka-server
  - docker build -t bgpark82/game-gateway ./gateway
  - docker build -t bgpark82/game-user ./user

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push bgpark82/game-multiplication
  - docker push bgpark82/game-eureka-server
  - docker push bgpark82/game-gateway
  - docker push bgpark82/game-user