version: '3'
services:

  eureka-server:
    build:
      context: eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: always
    networks:
      - game-network

  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - eureka-server
    networks:
      - game-network

  multiplication:
    build:
      context: multiplication
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - eureka-server
    networks:
      - game-network

  user:
    build:
      context: user
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - eureka-server
    networks:
      - game-network

networks:
  game-network: